// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stockly;

#nullable disable

namespace Stockly.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008154334_seeddata3")]
    partial class seeddata3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Stockly.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer_contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total_amount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000001",
                            Customer_name = "Customer 1",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 60m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000002",
                            Customer_name = "Customer 2",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 70m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000003",
                            Customer_name = "Customer 3",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 80m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000004",
                            Customer_name = "Customer 4",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 90m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000005",
                            Customer_name = "Customer 5",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 100m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000006",
                            Customer_name = "Customer 6",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 110m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000007",
                            Customer_name = "Customer 7",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 120m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000008",
                            Customer_name = "Customer 8",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 130m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000009",
                            Customer_name = "Customer 9",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 140m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000010",
                            Customer_name = "Customer 10",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 150m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000011",
                            Customer_name = "Customer 11",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 160m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000012",
                            Customer_name = "Customer 12",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 170m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000013",
                            Customer_name = "Customer 13",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 180m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000014",
                            Customer_name = "Customer 14",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 190m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000015",
                            Customer_name = "Customer 15",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 200m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000016",
                            Customer_name = "Customer 16",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 210m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000017",
                            Customer_name = "Customer 17",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 220m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000018",
                            Customer_name = "Customer 18",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 230m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000019",
                            Customer_name = "Customer 19",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 240m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000020",
                            Customer_name = "Customer 20",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 250m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000021",
                            Customer_name = "Customer 21",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 260m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000022",
                            Customer_name = "Customer 22",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 270m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000023",
                            Customer_name = "Customer 23",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 280m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000024",
                            Customer_name = "Customer 24",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 290m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000025",
                            Customer_name = "Customer 25",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 300m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000026",
                            Customer_name = "Customer 26",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 310m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000027",
                            Customer_name = "Customer 27",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 320m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000028",
                            Customer_name = "Customer 28",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 330m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000029",
                            Customer_name = "Customer 29",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 340m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000030",
                            Customer_name = "Customer 30",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 350m
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000031",
                            Customer_name = "Customer 31",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 360m
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000032",
                            Customer_name = "Customer 32",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 370m
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000033",
                            Customer_name = "Customer 33",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 380m
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000034",
                            Customer_name = "Customer 34",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 390m
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000035",
                            Customer_name = "Customer 35",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 400m
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000036",
                            Customer_name = "Customer 36",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 410m
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000037",
                            Customer_name = "Customer 37",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 420m
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000038",
                            Customer_name = "Customer 38",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 430m
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000039",
                            Customer_name = "Customer 39",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 440m
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000040",
                            Customer_name = "Customer 40",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 50m
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000041",
                            Customer_name = "Customer 41",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 60m
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000042",
                            Customer_name = "Customer 42",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 70m
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000043",
                            Customer_name = "Customer 43",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 80m
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000044",
                            Customer_name = "Customer 44",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 90m
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000045",
                            Customer_name = "Customer 45",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 100m
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000046",
                            Customer_name = "Customer 46",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 110m
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000047",
                            Customer_name = "Customer 47",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 120m
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000048",
                            Customer_name = "Customer 48",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 130m
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000049",
                            Customer_name = "Customer 49",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 140m
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000050",
                            Customer_name = "Customer 50",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 150m
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000051",
                            Customer_name = "Customer 51",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 160m
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000052",
                            Customer_name = "Customer 52",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 170m
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000053",
                            Customer_name = "Customer 53",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 180m
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000054",
                            Customer_name = "Customer 54",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 190m
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000055",
                            Customer_name = "Customer 55",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 200m
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000056",
                            Customer_name = "Customer 56",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 210m
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000057",
                            Customer_name = "Customer 57",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 220m
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000058",
                            Customer_name = "Customer 58",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 230m
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000059",
                            Customer_name = "Customer 59",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 240m
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000060",
                            Customer_name = "Customer 60",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 250m
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000061",
                            Customer_name = "Customer 61",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 260m
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000062",
                            Customer_name = "Customer 62",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 270m
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000063",
                            Customer_name = "Customer 63",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 280m
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000064",
                            Customer_name = "Customer 64",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 290m
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000065",
                            Customer_name = "Customer 65",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 300m
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2025, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000066",
                            Customer_name = "Customer 66",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 310m
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000067",
                            Customer_name = "Customer 67",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 320m
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2025, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000068",
                            Customer_name = "Customer 68",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 330m
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000069",
                            Customer_name = "Customer 69",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 340m
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000070",
                            Customer_name = "Customer 70",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 350m
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000071",
                            Customer_name = "Customer 71",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 360m
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000072",
                            Customer_name = "Customer 72",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 370m
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000073",
                            Customer_name = "Customer 73",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 380m
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000074",
                            Customer_name = "Customer 74",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 390m
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000075",
                            Customer_name = "Customer 75",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 400m
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000076",
                            Customer_name = "Customer 76",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 410m
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000077",
                            Customer_name = "Customer 77",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 420m
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2025, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000078",
                            Customer_name = "Customer 78",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 430m
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000079",
                            Customer_name = "Customer 79",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 440m
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000080",
                            Customer_name = "Customer 80",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 50m
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000081",
                            Customer_name = "Customer 81",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 60m
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000082",
                            Customer_name = "Customer 82",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 70m
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000083",
                            Customer_name = "Customer 83",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 80m
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000084",
                            Customer_name = "Customer 84",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 90m
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000085",
                            Customer_name = "Customer 85",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 100m
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000086",
                            Customer_name = "Customer 86",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 110m
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000087",
                            Customer_name = "Customer 87",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 120m
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000088",
                            Customer_name = "Customer 88",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 130m
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000089",
                            Customer_name = "Customer 89",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 140m
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000090",
                            Customer_name = "Customer 90",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 150m
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000091",
                            Customer_name = "Customer 91",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 160m
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000092",
                            Customer_name = "Customer 92",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 170m
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000093",
                            Customer_name = "Customer 93",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 180m
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000094",
                            Customer_name = "Customer 94",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 190m
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000095",
                            Customer_name = "Customer 95",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 200m
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000096",
                            Customer_name = "Customer 96",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 210m
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000097",
                            Customer_name = "Customer 97",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 220m
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000098",
                            Customer_name = "Customer 98",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 230m
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000099",
                            Customer_name = "Customer 99",
                            Payment_method = "Mada",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 240m
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customer_contact = "05000100",
                            Customer_name = "Customer 100",
                            Payment_method = "Cash",
                            Payment_notes = "Auto-generated test order",
                            Status = "approved",
                            Total_amount = 250m
                        });
                });

            modelBuilder.Entity("Stockly.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Stockly.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Storage_Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High performance laptop",
                            IsActive = true,
                            Name = "Laptop",
                            Price = 1200m,
                            Quantity = 10,
                            Storage_Note = "Keep dry"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest model smartphone",
                            IsActive = true,
                            Name = "Smartphone",
                            Price = 800m,
                            Quantity = 20,
                            Storage_Note = "Handle with care"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Noise cancelling headphones",
                            IsActive = true,
                            Name = "Headphones",
                            Price = 200m,
                            Quantity = 30,
                            Storage_Note = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mechanical keyboard",
                            IsActive = true,
                            Name = "Keyboard",
                            Price = 100m,
                            Quantity = 40,
                            Storage_Note = ""
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless mouse",
                            IsActive = true,
                            Name = "Mouse",
                            Price = 50m,
                            Quantity = 50,
                            Storage_Note = ""
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "24-inch full HD monitor",
                            IsActive = true,
                            Name = "Monitor",
                            Price = 250m,
                            Quantity = 15,
                            Storage_Note = ""
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All-in-one printer",
                            IsActive = true,
                            Name = "Printer",
                            Price = 300m,
                            Quantity = 5,
                            Storage_Note = ""
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "10-inch Android tablet",
                            IsActive = true,
                            Name = "Tablet",
                            Price = 400m,
                            Quantity = 12,
                            Storage_Note = ""
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wooden office desk",
                            IsActive = true,
                            Name = "Desk",
                            Price = 150m,
                            Quantity = 7,
                            Storage_Note = ""
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic office chair",
                            IsActive = true,
                            Name = "Chair",
                            Price = 180m,
                            Quantity = 9,
                            Storage_Note = ""
                        });
                });

            modelBuilder.Entity("Stockly.Models.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Change")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Product_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Related_Order_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Product_Id");

                    b.HasIndex("Related_Order_Id");

                    b.ToTable("StockAdjustment");
                });

            modelBuilder.Entity("Stockly.Models.OrderItem", b =>
                {
                    b.HasOne("Stockly.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stockly.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Stockly.Models.StockAdjustment", b =>
                {
                    b.HasOne("Stockly.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stockly.Models.Order", "Related_Order")
                        .WithMany()
                        .HasForeignKey("Related_Order_Id");

                    b.Navigation("Product");

                    b.Navigation("Related_Order");
                });

            modelBuilder.Entity("Stockly.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
